[project]
name = 'Temporal-Energy-Futures-Market-'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.time-crystal-energy-harvesting]
path = 'contracts/time-crystal-energy-harvesting.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
